language: node_js
node_js:
  - "5"

before_install:
  - sudo add-apt-repository ppa:pov/wkhtmltopdf
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz
  - sudo apt-get install -y wkhtmltopdf

install:
 - npm install
 - npm run clean
 - chmod u+x deploy.sh

script:
  - ./deploy.sh


env:
  global:
  - ENCRYPTION_LABEL: "c40f8a167d3c"

