language: node_js
node_js:
  - "5"

before_install:
  - wget http://download.gna.org/wkhtmltopdf/0.12/0.12.4/wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - tar xvf wkhtmltox-0.12.4_linux-generic-amd64.tar.xz
  - sudo apt-get -qq update
  - sudo apt-get install -y graphviz

install:
 - npm install
 - npm run clean
 - chmod u+x deploy.sh

script:
  - ./deploy.sh



env:
  global:
  - ENCRYPTION_LABEL: "c40f8a167d3c"

